// DigiFriend — Edge Function: create a call record
// Deploy: supabase functions deploy create-call
// Called by admin.html to create calls without writing SQL

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const SUPABASE_URL  = Deno.env.get('SUPABASE_URL')!
const SUPABASE_KEY  = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const ADMIN_SECRET  = Deno.env.get('ADMIN_SECRET')!

Deno.serve(async (req) => {
  // CORS
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: {
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Headers': 'content-type, x-admin-secret',
    }})
  }

  // Check admin secret
  const secret = req.headers.get('x-admin-secret')
  if (secret !== ADMIN_SECRET) {
    return new Response(JSON.stringify({ error: 'Unauthorized' }), { status: 401 })
  }

  const { member_email, friend_name, friend_flag, friend_email, scheduled_at, duration_minutes } = await req.json()

  if (!member_email || !friend_name || !scheduled_at) {
    return new Response(JSON.stringify({ error: 'Missing required fields' }), { status: 400 })
  }

  const sb = createClient(SUPABASE_URL, SUPABASE_KEY, {
    auth: { autoRefreshToken: false, persistSession: false }
  })

  // Look up member by email
  const { data: users, error: userErr } = await sb.auth.admin.listUsers()
  if (userErr) return new Response(JSON.stringify({ error: userErr.message }), { status: 500 })

  const member = users.users.find(u => u.email === member_email)
  if (!member) {
    return new Response(JSON.stringify({ error: `No user found with email: ${member_email}` }), { status: 404 })
  }

  // Create call — jitsi_room is auto-generated by DB trigger
  const { data: call, error: callErr } = await sb
    .from('calls')
    .insert({
      member_id: member.id,
      friend_name,
      friend_flag: friend_flag || '🌍',
      scheduled_at,
      duration_minutes: duration_minutes || 60,
    })
    .select()
    .single()

  if (callErr) return new Response(JSON.stringify({ error: callErr.message }), { status: 500 })

  // Store match info + set matched=true on the member
  await sb.auth.admin.updateUserById(member.id, {
    user_metadata: {
      ...member.user_metadata,
      matched: true,
      friend_name,
      friend_flag: friend_flag || '🌍',
      friend_email: friend_email || null,
    }
  })

  return new Response(JSON.stringify({
    success: true,
    call,
    jitsi_url: `https://meet.jit.si/${call.jitsi_room}`,
  }), {
    headers: {
      'Content-Type': 'application/json',
      'Access-Control-Allow-Origin': '*',
    }
  })
})
